### ISSUE TITLE
Traditional Character in Simplified Chinese Mode

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#357]
## Expected behavior

As I choose Simplified Chinese Mode, I expected all the characters are simplified chinese, but there's traditional chinese characters.

## Actual behavior

There are Traditional Chinese Character in Simplified Chinese mode on the welcome page starting from "双关语“. The above paragraph are consist of all Traditional Chinese Characters "無論您的能力如何，都可以透過世界語言中的動畫單字、表情符號和符號來學習編碼。
Wordplay 是一種創新的程式語言 🖥︎️，具有區塊和文字編輯 📝︎、時間 🕦︎、聲音 🎤︎、網頁 🔗︎ 和物理 🌎︎ 等有趣的輸入、即時時間旅行調試 ⏪︎ 以及全面的文檔 🗂︎️。 所有這些都在不斷增長的世界語言清單中🌐︎，遵循最新的網路可訪問性標準♿︎️。 與朋友、私人團體或全世界分享↗︎️。 永遠免費來自"

## Screenshots

<img width="1440" alt="截屏2024-01-24 下午5 47 46" src="https://github.com/wordplaydev/wordplay/assets/146252292/52c10e7a-5b49-416e-9b1e-f11aa378437b">

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not. Don't skip these; cross-browser issues are a common cause of problems.

Desktop

-   mac OS 12.6.6
-  Chrome 120.0.6099.129

**Comment by Marc0Guo** [comment]
I noticed the error was in main zh-cn-tutorial line 4103 and 4104. I will try to fix it.

**Comment by amyjko** [comment]
Thanks @Marc0Guo! Remember, when you claim an issue, assign yourself, so others no you're working on it. I look forward to the PR.

**Comment by Marc0Guo** [comment]
I will do that!

**Comment by Kwang37** [comment]
Could I work this issue with u

**Comment by amyjko** [comment]
@Kwang37, I assume you're asking @Marc0Guo? (It helps to tag people directly; GitHub can be configured to only do notifications for when you're tagged, so @Marc0Guo might not see this without tagging).

**Comment by Marc0Guo** [comment]
> Could I work this issue with u

@Kwang37 Sure.

**Comment by amyjko** [comment]
@Marc0Guo why is this closed? If the issue is resolved, then it should be a pull request to merge into main. If its no longer an issue, you should explain why you closed it here.

**Comment by Marc0Guo** [comment]
@amyjko I'm sorry I made a mistake here. There was still something wrong with the code so I cannot make a pull request. I will fix it as soon as possible.

**Comment by amyjko** [comment]
Let me know how I can help. (Also, the proper way to close an issue, per the wiki, is to include "fixed #nnn" in a commit message, so we know which commit resolved the issue).

**Comment by Marc0Guo** [comment]
The problem is probably due to the zh-CN locale is outdated, Ben is going to update it tonight. If the problem still exist, I will fix it.

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by amyjko** [comment]
No reply :( Unassigning @Marc0Guo.

**Comment by Marc0Guo** [comment]
The problem exists because of rebasing error. The code for the lines was missing somehow in zn-ch but appears in main. Ben was trying to do rebasing at the end of last quarter but there was a lot of error. Looks like the rebasing is done right now. I found the error code starting from line 4167 in zn-ch, I will fix it this week. ('m going to be volunteering this quarter.)

**Comment by amyjko** [comment]
Thanks @Marc0Guo!

**Comment by Marc0Guo** [comment]
The problem was fixed by someone else as I did git pull today on line 4170 to 4172 in "chinese simplified" branch.

**Comment by yishiz2** [comment]
Looks like there are still traditional and simplified Chinese mixed together. I am working on it.

**Comment by yishiz2** [comment]
@Marc0Guo Are you still working on this?

**Comment by Marc0Guo** [comment]
@yishiz2 When I checked the code, the translation was corrected in both zn-ch and main branch.

**Comment by yishiz2** [comment]
@Marc0Guo Sorry I was working on another issue and did not see this, but that is interesting... I am still seeing this on my end.



![Image](https://github.com/wordplaydev/wordplay/assets/122429712/4c486d43-10b8-4262-9d2b-94cfee572cd9)

**Comment by Marc0Guo** [comment]
@yishiz2 I believe the branch on the website is different than the one you are currently working. The issue will be fixed as the current working zn-ch branch is merged to the website branch.

**Comment by joonpiter** [comment]
Hi @Marc0Guo and @yishiz2 will you guys be going forward with this issues, if not ill unassign you

**Comment by amyjko** [comment]
No reply from either, unassigning.

**Comment by amyjko** [comment]
I believe these were resolved by earlier pull requests, but not linked to this issue.
